# NOT FOR PRODUCTION USE
set BASE /Users/jason/Code/marketplace

## Signing Key
set -x MP_SIGNING_KEY GDCYZAVRTZTQ2TEDWZ6KXOHSUCQUVJD5XA2BTT72URVWDX3NGIDSZOBG
set -x MP_SIGNING_KEY_SEED SCYSAZCQUN3LNEPBITBZQXN3WPLODUGT4H54UL7PTCOHEBBF6OCG7HEF

## Test Client
set -x MP_CLIENT_SIGNING_KEY GBULBWFJCGZTSCYQH3RXNDTB34MGI2JMAR3BPM3X66W2X3D2HVJ4NORW
set -x MP_CLIENT_SIGNING_KEY_SEED SCHVZHXDKFVG572PEPEUYOML4QNO6WP6HOQVGL4ZU47HIOHLGAQGHQHH

## Endpoints
set -x MP_WEB_AUTH_ENDPOINT https://localhost:3000/token
set -x MP_TRANSFER_SERVER https://localhost:3001

## TLS
set -x MP_TLS_CERT_PATH $BASE/mp-common/test/server.crt
set -x MP_TLS_KEY_PATH $BASE/mp-common/test/server.key
